version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .development.env
    depends_on:
      - db
    volumes:
      - /app/node_modules
      - ./src:/app/src
  db:
    container_name: postgres
    image: 'postgres:latest'
    env_file:
      - .development.env
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data